site_name: gensor
repo_url: https://github.com/zawadzkim/gensor
site_url: https://zawadzkim.github.io/gensor
site_description: Library for handling groundwater sensor data.
site_author: Mateusz Zawadzki
edit_uri: edit/main/docs/
repo_name: zawadzkim/gensor
copyright: Maintained by <a href="https://zawadzkim.com">Mateusz</a>.

watch:
  - ./gensor

nav:
  - Home: index.md
  - Modules: modules.md

strict: false
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          options:
            show_submodules: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: false
            heading_level: 2
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zawadzkim/gensor
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/gensor

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
