name: Build GitHub Pages
on:
  workflow_run:
    workflows: ["Quality control"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_mkdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Build MkDocs site
        run: poetry run mkdocs gh-deploy --config-file mkdocs.yml --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
